### ISSUE TITLE
Is there a Todo list or roadmap for the software?  

### ISSUE THREAD

**Issue by Pillar1989** [EmbeddedRPC/erpc#109]
@MichalPrincNXP What is the future of the software?

**Comment by MichalPrincNXP** [comment]
Hello @Pillar1989 , the erpc project development continues, the goal is to provide at least two releases per year (aligned with NXP MCUXpressoSDK releases). The list of tasks, todos, bugs is maintained internally. We are trying to address this Github community issues and pull requests first. Except of bugfixing and accepting new community pull request, new transports are planned for the next release. Hope it helps.

**Comment by Pillar1989** [comment]
Thank you for your answer. When is the next release? What feature is new transports? Can you divulge?  @MichalPrincNXP

**Comment by MichalPrincNXP** [comment]
The next release is planned in 6 months (beg. of January). New transports means we are going to add support for new transport layers: except of RPMsg_Lite, UART, SPI, serial, TCP, MU - based transports (currently available) there is a plan to support transports based on Linux SPIdev and I2C.

**Comment by Pillar1989** [comment]
Thanks
