### ISSUE TITLE
multiple definition of g_client

### ISSUE THREAD

**Issue by dpfrey** [EmbeddedRPC/erpc#113]
I have been trying to build some simple examples using eRPC and I ran into this problem:

```
g++ -I gen -I /home/dfrey/sw/erpc-1.7.4/include/erpc -L /home/dfrey/sw/erpc-1.7.4/lib -o counter_client_test counter_client_test.o erpc_setup_tcp_transport.o counter_client.o -l erpc -l pthread
/usr/bin/ld: /home/dfrey/sw/erpc-1.7.4/lib/liberpc.a(erpc_client_setup.o):/home/dfrey/upstream_source/erpc/erpc_c/setup/erpc_client_setup.cpp:30: multiple definition of `g_client'; /home/dfrey/sw/erpc-1.7.4/lib/liberpc.a(erpc_arbitrated_client_setup.o):/home/dfrey/upstream_source/erpc/erpc_c/setup/erpc_arbitrated_client_setup.cpp:33: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:20: counter_client_test] Error 1
```

It looks like both `erpc_c/setup/erpc_arbitrated_client_setup.cpp` and `erpc_c/setup/erpc_client_setup.cpp` both define a global variable named `g_client`.  Is this intentional?  I found that I had to delete the "arbitrated" version from the `SOURCES` list in the eRPC Makefile in order to get my code to build and run.

This is the example code: https://github.com/dpfrey/erpc_examples/tree/master/counter_c

**Comment by MichalPrincNXP** [comment]
Hi, sorry for late response and thanks for reporting it ... this issue is being solved in #151
