### ISSUE TITLE
Does erpc support Vxworks?

### ISSUE THREAD

**Issue by aohwang** [EmbeddedRPC/erpc#115]
I am finding one lightweight rpc framework for Vxworks platform. Is the erpc supported on Vxworks? Are there some dependencies not working with Vxworks? Thanks sincerely

**Comment by Hadatko** [comment]
Hi @aohwang , currently vxworks is not supported. You can create few port files to add support. See similar thread.

https://github.com/EmbeddedRPC/erpc/issues/104
