### ISSUE TITLE
Publish eRPC to pypi automatically

### ISSUE THREAD

**Issue by Hadatko** [EmbeddedRPC/erpc#142]
Hi @MichalPrincNXP, as you are owner of eRPC account on pypi i wanted to ask you to implement this feature:
https://github.com/marketplace/actions/pypi-publish
You will set action "on push to master branch" publish ePRC to pypi. So you don't need to do it manually in future .... In link is description how to do it. Theoretically i can help with start...

**Comment by MichalPrincNXP** [comment]
Thanks, will do it before 1.8.0 release.

**Comment by MichalPrincNXP** [comment]
After looking at the PyPI publish GitHub Action in details, the benefit of the use in our case is not so high and the decision has been made to stay with the current manual PyPi update. Thank you.
