### ISSUE TITLE
Multiple erpc requests processing (server side)

### ISSUE THREAD

**Issue by tmordeko** [EmbeddedRPC/erpc#150]
Hi,

Assuming 2 cores (A+B) communicating over serial interface, like UART, A core acting as client and B as rpc server.

Is it possible to process multiple requests (on the server side) coming from two different threads A.1 and A.2 simultaneously ?

A.1 ----first erpc msg  ---> B
context switch A
A.2 ----first erpc msg ---> B

How B will handle this scenario ?

/Tzvika

**Comment by MichalPrincNXP** [comment]
Hi, I am afraid issuing erpc requests simultaneously from two tasks is not possible, unless there is any mechanism implemented on the application level that would allow requests serialization. Consider wrapping erpc calls in each task by an inter-task mutex lock that would ensure single request-response communication is performed as one operation.

**Comment by tmordeko** [comment]
Hi, Thanks @MichalPrincNXP this is what I suspected :-) 
I saw that there is client arbitrator for sharing client-server communication channel isn't there a similar mechanism to handle multiple server requests, working in the granularity of a single erpc message, meaning the server will be able to process multiple messages but not necessarily associated with the same erpc request  (in OS environment off course)

Thanks in advance,
Tzvika

**Comment by Hadatko** [comment]
Technicaly i think you can have several server objects but every server need its own transport (communicate trough different transport).

**Comment by tmordeko** [comment]
Thanks @Hadatko , technically the same client instance can be used from multiple tasks.

**Comment by Hadatko** [comment]
Yes, but you should wait until one rpc call will be completly done until call another one. Maybe you can use oneway type function where client is not waiting for answer. And get ouputs later. Depends on your use case...

**Comment by tmordeko** [comment]
Thanks all for the answers
