### ISSUE TITLE
Multiple clients

### ISSUE THREAD

**Issue by massimobadanai** [EmbeddedRPC/erpc#164]
Hi all,
is it possibile to create two clients ( on the same application) with two different transports? I would like to have a client over USB Bulk and another client over USB CDC...but i don't know if there is a way to do this....
Best Regards,
Massimo

**Comment by infn-ke** [comment]
I believe two clients and two transports should work. One client and two different transports, is however not possible. See

https://github.com/EmbeddedRPC/erpc/issues/152

**Comment by mazent** [comment]
what about g_client?

**Comment by infn-ke** [comment]
You want to do two clients in one Linux process or in one RTOS? That won't work due to no context in client interface, same issue as in #152.
