### ISSUE TITLE
Signature mismatch between erpc::Transport::send and erpc::InterThreadBufferTransport::send

### ISSUE THREAD

**Issue by yoshinao-takada** [EmbeddedRPC/erpc#172]
The two functions had different signatures and I could not instantiate InterThreadBufferTransport object.
Could you please correct definitions of the send() methods. I thought that the definition of InterThreadBufferTransport was
adequate but most of Transport children classes have the definitions same as Transport base class. I could not determine which should be correct, 'const' or no 'const'.

**Comment by MichalPrincNXP** [comment]
Hello @yoshinao-takada , thanks for reporting. The InterThreadBufferTransport is not used much now (kind of obsolete). Anyway, it should has the send method with no-cost as the Transport class defines: virtual erpc_status_t send(MessageBuffer *message) = 0;
I will fix it.

**Comment by MichalPrincNXP** [comment]
solved by https://github.com/EmbeddedRPC/erpc/commit/f99e25233370752c6c9f88390e6652a271ff617b
