### ISSUE TITLE
generate python shim code from erpc

### ISSUE THREAD

**Issue by drumairali** [EmbeddedRPC/erpc#205]
there is option to generate C code from erpc using erpcgen but how can we generate python shim code from erpc. if i want to execute python on on client side and C on server side can anyone refer me any example of it ?

**Comment by MichalPrincNXP** [comment]
Hi @drumairali , shim code for Python is generated the same way as for C, just the -g py parameter needs to be added on the command line, see https://github.com/EmbeddedRPC/erpc/wiki/erpcgen.
As for the example, again see the answer in #186 . Thank you.
