### ISSUE TITLE
How to notify the client when the server receives an interrupt

### ISSUE THREAD

**Issue by Zengjie12138** [EmbeddedRPC/erpc#216]
**Server(cortex-M4 and C)  <-------->  Client(PC and python)**
Hi,
now I have implemented the remote call of the server function through the client,
but I don't know  how to notify the client when the server receives an interrupt,
is there any good way.
Thanks.

**Comment by MichalPrincNXP** [comment]
Hello @Zengjie12138 , what transport layer are you using? Are you asking for a mechanism that would notify the client that the server received the erpc request? I guess you are using oneway erpc requests (not expecting any return value), is that your case?
Regards
Michal
