### ISSUE TITLE
Is it possible notify data from server to client

### ISSUE THREAD

**Issue by hyller** [EmbeddedRPC/erpc#221]
This is a good client/server erpc. The basic mode is that client send a remote call to server, then server give response. Is it possible server notify or push data to client at any time? Or is it possible implement both client and server on one node? For example two node A and B. Most of time, A can send call to B and wait response. But some case, B needs to send data to A initiatively, how can achieve it?

**Comment by MichalPrincNXP** [comment]
Hello @hyller ,
the solution of your case is the transport arbitrator. You can get more info from following discussions (incl. where to obtain an example projects): #80 , #62 

Regards
Michal

**Comment by hyller** [comment]
Thanks Michal, it is what I want to have.
