### ISSUE TITLE
Multithreading of servers when built with an RTOS

### ISSUE THREAD

**Issue by ablaylock** [EmbeddedRPC/erpc#25]
The documentation in the home/introduction makes reference of "Multithreading of servers when built with an RTOS" but I am unable to see how any of the threading support works for servers. I take the statement to mean that rpc calls may be handled by separate threads. I only see the TCPTransport having any mention of threads and it only creates one thread to run the server, and doesn't seem to spawn threads to call the rpc endpoints. 

Have I misinterpreted the intended threading support?

**Comment by Hadatko** [comment]
Hi currently we don't have example of multithreading of servers. But basically you can create several severs and run each in their own task/thread. Setup function don't support multithreading case, but you can use them as template to create more of them.
