### ISSUE TITLE
Optional memory smashing with big length

### ISSUE THREAD

**Issue by amgross** [EmbeddedRPC/erpc#256]
In case of very big length here:
https://github.com/EmbeddedRPC/erpc/blob/c8adbf8c17bfb282284e730a55a0e9e11d065091/erpc_c/infra/erpc_message_buffer.cpp#L27
https://github.com/EmbeddedRPC/erpc/blob/c8adbf8c17bfb282284e730a55a0e9e11d065091/erpc_c/infra/erpc_message_buffer.cpp#L48
there may be wraparound.

By the way, who is using those functions?

**Comment by Hadatko** [comment]
HI @amgross, thank you for your input. 
What do you mean with your last question?

**Comment by amgross** [comment]
I tried to find in your code usage of:
https://github.com/EmbeddedRPC/erpc/blob/c8adbf8c17bfb282284e730a55a0e9e11d065091/erpc_c/infra/erpc_message_buffer.cpp#L23
https://github.com/EmbeddedRPC/erpc/blob/c8adbf8c17bfb282284e730a55a0e9e11d065091/erpc_c/infra/erpc_message_buffer.cpp#L44

And I couldn't find such. so I thought maybe those functions can be erased.

**Comment by Hadatko** [comment]
Write is used now in PR :D I would keep functions as they may be usefull in future.
What do you think about PR?

**Comment by amgross** [comment]
Looks good, you can close the issue I think

**Comment by Hadatko** [comment]
PR was merged
