### ISSUE TITLE
Unneeded length 0 checking

### ISSUE THREAD

**Issue by amgross** [EmbeddedRPC/erpc#257]
You are checking that length is not 0 for memset here:
https://github.com/EmbeddedRPC/erpc/blob/c8adbf8c17bfb282284e730a55a0e9e11d065091/erpc_c/infra/erpc_message_buffer.cpp#L33-L36
https://github.com/EmbeddedRPC/erpc/blob/c8adbf8c17bfb282284e730a55a0e9e11d065091/erpc_c/infra/erpc_message_buffer.cpp#L54-L57
According what I saw, it is OK to give memset 0 length but not NULL pointer.

I think you should:
(A) Check for error case where `data == NULL` and `length > 0`, like done at:https://github.com/EmbeddedRPC/erpc/blob/c8adbf8c17bfb282284e730a55a0e9e11d065091/erpc_c/infra/erpc_message_buffer.cpp#L131-L134
https://github.com/EmbeddedRPC/erpc/blob/c8adbf8c17bfb282284e730a55a0e9e11d065091/erpc_c/infra/erpc_message_buffer.cpp#L105-L108

(B) Check if `data` is NULL (and `length == 0`) and not do memset (this should be done in all code mentioned above)

**Comment by Hadatko** [comment]
Please check new PR if it is ok to you
