### ISSUE TITLE
erpc_rpmsg_lite_transport.cpp

### ISSUE THREAD

**Issue by VFSAS** [EmbeddedRPC/erpc#26]
please check rpmsg_lite_master_init() and rpmsg_lite_remote_init() functions in
erpc_rpmsg_lite_transport.cpp. The bare metal compilation works without last parameters in these functions.

**Comment by Hadatko** [comment]
Hi @VFSAS,
if you were on master branch can you try current version?

**Comment by VFSAS** [comment]
Hi, Dusan,
I'm not sure now, I used erpc develop branch and rpmsg-lite master one 1.1.0.
P.S.  the reason for using bare metal transport was to compare M4-A9 speed with/without RTOS on M4 using eRPC.
But as I mentioned in other issue the speed in both cases was to slow for me...
Now I am trying work on rpmsg transport level...
