### ISSUE TITLE
Annotation for a language

### ISSUE THREAD

**Issue by nchokoev** [EmbeddedRPC/erpc#27]
Hi,
I try to use @external for C only, but get an exception "Unexpected :"

the format I'm using is:
@c:external

ERPC1.5

Is that the correct usage?

**Comment by Hadatko** [comment]
Hi @nchokoev,
It's likely possible supported for next version of eRPC.

**Comment by nchokoev** [comment]
Hi @Hadatko,
Is it implemented in any branch currently?

**Comment by Hadatko** [comment]
Hi @nchokoev try develop branch.

**Comment by Hadatko** [comment]
Today i merged develop branch to master branch. Everything should be up-to-date.
