### ISSUE TITLE
[QUESTION] increase packet size tcp 

### ISSUE THREAD

**Issue by flo-th** [EmbeddedRPC/erpc#272]
Hi all,

Using a python client with a C server, with tcp transport, how could i increase the tcp packet size which seems limited to 256 bytes.

Thanks in advance.

**Comment by flo-th** [comment]
Hi @Hadatko, 
I have already tried to increase the value of ERPC_DEFAULT_BUFFER_SIZE and check it new value, but it never receive the data from the python client.

**Comment by Hadatko** [comment]
Currently i don't see the reason. Which message buffer are you using on C? We are preparing tcp python tests which will also communicate with C tcp test. So it will be easier to test, but not sure how soon this will be available

**Comment by Hadatko** [comment]
Also are you sure you are using correct config file? Sometimes people copy template modify it and they will add include path to the template origin.

**Comment by flo-th** [comment]
I am using a binary message buffer on C.
Where could i investigate to see the drop of my packet before the calling of rpc method ?
