### ISSUE TITLE
How to convert C header to eRPC IDL file

### ISSUE THREAD

**Issue by sudhakarreddi** [EmbeddedRPC/erpc#28]
Hi All,

I would like to use eRPC for one of my project. I am looking for option, is there any way to convert C language header file to eRPC IDL file. I have a large chunk of C header file so I am finding it difficult to write the eRPC IDL file manually.  Appreciate your help in this regard. Thank you for your help.

Regards,
Sudhakar

**Comment by Hadatko** [comment]
Hi @sudhakarreddi ,
this is also one of our goal. To create parser for C header file. But it is not done yet.

**Comment by sudhakarreddi** [comment]
Hi @Hadatko ,
Thank you for quick response.  Is it coming any time sooner ? If yes I probably wait for some time. Please let me know ?

Regards,
Sudhakar

**Comment by Hadatko** [comment]
Hi, 
currently we don't have estimation for new features.

**Comment by nchokoev** [comment]
We use python script and ctags (http://ctags.io/) to convert c headers to .erpc.

**Comment by Pratyush-Mallick** [comment]
> We use python script and ctags (http://ctags.io/) to convert c headers to .erpc.

Hi Nikolay, 

Can you provide more information on this?

**Comment by pmallick-adi** [comment]
Someone please help me with this.
