### ISSUE TITLE
[QUESTION] How to generate Python files when IDL files contain C headers?

### ISSUE THREAD

**Issue by henrifrancois** [EmbeddedRPC/erpc#285]
**If you didn't find answer in existing open/closed issues you may ask here**

When generating Python files using .erpc IDL files which contain C header files, `client.py` contains an import statement for the C header, and `interface.py` does not contain anything other than an `import erpc` statement. Has anyone else experienced this? Am I missing something and this is a formal bug? This seems to be an issue with erpcgen directly. 

**Steps you didn't forgot to do**

- [X] I checked if there is no related issue opened/closed.
- [X] I checked that there doesn't exist opened/closed PR which is solving this issue.
- [X] I looked in documentation if there is related information.

**Comment by Hadatko** [comment]
HI @henrifrancois , could you post erpc file so i can doublecheck its output?

**Comment by henrifrancois** [comment]
Hi @Hadatko, I cannot post the files due to their sensitive nature and complexity. I am finding it difficult to reproduce the issue on small files. I will try to update in the next 24 hours on my efforts to reproduce the issue with a minimal example.

**Comment by henrifrancois** [comment]
for reference when using erpcgen I receive several instances of "invalid map key: mlComment" as an error.

**Comment by henrifrancois** [comment]
As you recommended, changing `@include` annotations to `@c:include` as well as `@external` to `@c:external` seemed to have solved this issue for me. I will mark this as closed.
