### ISSUE TITLE
PendingClientInfo m_next not updated when aded to active list

### ISSUE THREAD

**Issue by bartro** [EmbeddedRPC/erpc#291]
In TransportArbitrator::addPendingClient, when a PendingClientInfo object is removed from a free list that contains multiple objects, its m_next will point to the next object on that free list.
If m_clientLisst is NULL, it will be set to this object but m_next is not updated and will point to an object on the free list.

Issue:
   // Add to active list.
    if (!m_clientList)
    {
        m_clientList = info;
    }
    else
    {
        info->m_next = m_clientList;
        m_clientList = info;
    }

Proposed fix:
    // Add to active list.
    info->m_next = m_clientList;
    m_clientList = info;

**Comment by Hadatko** [comment]
Hi @bartro , the fix is already in place: https://github.com/EmbeddedRPC/erpc/pull/199/files

**Comment by bartro** [comment]
@Hadatko Thank you, is there a known date for when a release with this fix will be available?

**Comment by Hadatko** [comment]
@MichalPrincNXP should be able to answer this question.

**Comment by MichalPrincNXP** [comment]
It has been released yesterday, see https://github.com/EmbeddedRPC/erpc/releases
