### ISSUE TITLE
Is ERPC support Windows platform?

### ISSUE THREAD

**Issue by PierrePeng** [EmbeddedRPC/erpc#299]
I wonder if ERPC could run on windows? Because I see WIN32 API is used in the project.

**Comment by thewon86** [comment]
I need it also.
Today, I build erpc in Cygwin32/64 environment , but it can't be used in Qt5 with MinGW.
When build erpc in Qt5 with MinGW, there are lots errors.

**Comment by Hadatko** [comment]
Hi, 
erpcgen can be built under windows in Visual Studio (but we are providing executable files in releases). This application is used to generated shim code for eRPC applications. 
eRPC lib can be likely built only for Linux. You should be likely possible to built app for windows with serial transport. We are not focusing on supporting windows eRPC applications. But you should be able to do it if you implement transport (other than serial) for windows.

**Comment by thewon86** [comment]
Thanks,
I did it. it works. now, erpc_tcp_transport can be compiled with MinGW / cygwin GCC / linux GCC at the same time.

**Comment by huiyeruzhou** [comment]
> Thanks, I did it. it works. now, erpc_tcp_transport can be compiled with MinGW / cygwin GCC / linux GCC at the same time.

Hi, I'm trying the same as you did and notice that `erpc_tcp_transport.cpp` includes some header files that are not exist in Windows. Should I use winsock to implement it?
By the way, the motivation to compile erpc in windows is that I want use the class designer in VS to generate UML for erpc, maybe there is a better way to do it >_<...

**Comment by thewon86** [comment]
> 

https://thewon.gitee.io/2022/0902/erpc-transport-winsock2/

**Comment by Hadatko** [comment]
Hi @thewon86 , could you provide PR?
