### ISSUE TITLE
[BUG] using constant variable in enum, get wrong value

### ISSUE THREAD

**Issue by thewon86** [EmbeddedRPC/erpc#308]
**Describe the bug**

*IDL definition:*
```
const int32 matrix_size = 5;

type Matrix = int32[matrix_size][matrix_size];
```

*generated C code:*
```
typedef int32_t Matrix[5][5];

extern const int32_t matrix_size;
```

*IDL definition:*
```
enum enumColor {
    red,
    green = 10,
    blue = 2 * 10
}
```

*generated C code:*
```

typedef enum enumColor {
    red,
    green = 10,
    blue = 20
} enumColor;
```

*IDL definition:*
```
const int32 color_val = 5;

enum enumColor {
    red,
    green = 2 * color_val,
    blue = 2 * 10
}
```

*generated C code:*
```
typedef enum enumColor {
    red,
    green = 10,
    blue = 20
} enumColor;
```

All above are ok, but

*IDL definition:*
```
const int32 color_val = 5;

enum enumColor {
    red,
    green = color_val,
    blue = 2 * 10
}
```

*generated C code:*
```
typedef enum enumColor {
    red,
    green = 1,
    blue = 20
} enumColor;
```

green is 1, but not 5!
Then, if 

*IDL definition:*
```
const int32 color_val = 5;

enum enumColor {
    red,
    green = 1 * color_val,
    blue = 2 * 10
}
```

*generated C code:*
```
typedef enum enumColor {
    red,
    green = 5,
    blue = 20
} enumColor;
```

green is 5!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if there is no related issue opened/closed.
- [X] I checked that there doesn't exist opened PR which is solving this issue.

**Additional context**

**Comment by Hadatko** [comment]
Hi @thewon86 , thank you for creating PR. As you can see, PR for this fix was created. Until it will be released you can take changes and build application with fix.
