### ISSUE TITLE
ERPC_TYPE__DEFINITIONS when multiple distinct clients are used

### ISSUE THREAD

**Issue by Diagano** [EmbeddedRPC/erpc#336]
Hi,

Will try to keep short and to the point as this is not that big of a deal, here is our use case:
We have multiple groups working of the same platform but on different aspects of our platform. We do not want nor do we Intersect with the other clients which expose completly different set of functionalities to other cores on seperate transports and managed by different groups.
Now what I am concerned about is the fact that common header content is protected from redefinition by #ifndef/#define ERPC_TYPE_DEFINITIONS. Which will conflict if any code attempts to use more than once of these ERPC apps.
I found [this discussion](https://github.com/EmbeddedRPC/erpc/pull/181) but I don't think its relevant to my case.

Is there any way to control this other than the obvious manual modification or tinkering with the generator code?
If not I would lilke to suggest considering doing so at least in the appplication level, that is for top level IDL

progarme **<program_name>**

the define to be:

ERPC_**<program_name>**_TYPE_DEFINITIONS.

Thank you

**Comment by Hadatko** [comment]
Hi, sounds good to me.

**Comment by Hadatko** [comment]
Hi @Diagano , i made changes based on your requests. Until the changes will be merged to master you can take changes to your fork and compile erpcgen on your own and use it. 

In 1-2weeks there should be also other PR merged, which will build binaries for Linux and Mac within every PR and make it available for all users.

**Comment by Diagano** [comment]
That was quick :)
Thank you, will have a look and will replace my own simplified local changes (that are likely not properly covering all cases)

**Comment by Hadatko** [comment]
Happy to help ;)

**Comment by Hadatko** [comment]
Well i am about to delete this option anyway due to develop on other issue. The header file will be always created.

**Comment by Diagano** [comment]
> Well i am about to delete this option anyway due to develop on other issue. The header file will be always created.

Maybe this merits a seperate Q :)
I liked the fact that the common types do not repeat in each header when using @types_header. So after you delete this option a common header file will always be created + the specific headers will still hold the common types under ERPC_TYPE_DEFINITIONS ?

**Comment by Hadatko** [comment]
Common declarations will be only in one file.
