### ISSUE TITLE
Optional undefined behavior of memcpy

### ISSUE THREAD

**Issue by amgross** [EmbeddedRPC/erpc#350]
As described at #241 , it is undefined behavior to call memcpy with NULL pointer, even if length is 0.
https://github.com/EmbeddedRPC/erpc/blob/6756f3898cb72b401ffbf414ea65068809ff6132/erpcgen/src/templates/c_coders.template#L66-L73
Here, if {$info.name} is NULL and {$info.sizeTemp} is 0 this undefined behavior will be reached.

**Comment by amgross** [comment]
Seems like this issue is new from #72

**Comment by Hadatko** [comment]
Nice catch. You are right. I will fix this shortly and i will add issue that we can consider macro for checking parameter validation, or our own memcpy function implementation
