### ISSUE TITLE
Returning wrong error code for SpidevMaster receive

### ISSUE THREAD

**Issue by bastivi** [EmbeddedRPC/erpc#364]
https://github.com/EmbeddedRPC/erpc/blob/e8e2e633f23948291b2191a93a13927cd160843d/erpc_c/transports/erpc_spidev_master_transport.cpp#LL220C33-L220C33

Gusse the error code in line mentioned above should be "kErpcStatus_ReceiveFailed"

**Comment by Hadatko** [comment]
Hi @bastivi , make sense. I will repair that
