### ISSUE TITLE
[BUG] It seems mingw support dosen't work

### ISSUE THREAD

**Issue by thewon86** [EmbeddedRPC/erpc#366]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/EmbeddedRPC/erpc/assets/8926553/d7231d9c-2fff-4ca9-967c-aca2d6df1441)

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [x] I checked if there is no related issue opened/closed.
- [x] I checked that there doesn't exist opened PR which is solving this issue.

**Additional context**

**Comment by Hadatko** [comment]
Hi @thewon86, in develop branch only generating erpcgen works. In your PR i am also generating tests so if this messages are related to your PR we can talked about that under it.
