### ISSUE TITLE
[QUESTION] dose this project still maintained

### ISSUE THREAD

**Issue by amgross** [EmbeddedRPC/erpc#429]
Hi @Hadatko @MichalPrincNXP , dose this repository is still maintained?

For a long time there wasn't change and for longer there werent answers to questions.

- [x] I checked if there is no related issue opened/closed.
- [x] I checked that there doesn't exist opened/closed PR which is solving this issue.
- [x] I looked in documentation if there is related information.

**Comment by MichalPrincNXP** [comment]
Hello @amgross , the new release has been done recently: https://github.com/EmbeddedRPC/erpc/releases/tag/1.13.0
The project is in maintenance mode now due to limited capacities, will try to go through open issues and PR soon ...
Regards
Michal

**Comment by amgross** [comment]
OK, thank you very much for this great repo (:
