### ISSUE TITLE
Serial test fail

### ISSUE THREAD

**Issue by jpacheco8** [EmbeddedRPC/erpc#43]
When I run any serial test in Linux the following error appears:

Starting ERPC server...
test_lists_server_serial_test: /erpc-master/erpc_c/infra/erpc_framed_transport.cpp:67: virtual erpc_status_t erpc::FramedTransport::receive(erpc::MessageBuffer*): Assertion `m_crcImpl && "Uninitialized Crc16 object."' failed.
Aborted

**Comment by LiePy** [comment]
I also couldn't successfully test serial port based eRPC, I used virtual serial port created by "socat", maybe it doesn't support virtual serial port. I want to know if there is any problem with my code. 
    Do we have the eRPC demo based on serial port？

**Comment by MichalPrincNXP** [comment]
Hi, unfortunately there is no example showing the serial transport usage. It deals with not-maintained transport.
