### ISSUE TITLE
CRC annotation

### ISSUE THREAD

**Issue by nchokoev** [EmbeddedRPC/erpc#45]
What's the right use of @crc annotation?
From what I read it should create s constant crc16 based on the idl file and use it instead the crc16 over the message content. Is that correct?
I don't see methods on the transport layer (both C and Py) to allow this.

**Comment by Hadatko** [comment]
Hi @nchokoev,
which version of eRPC are you using? If last, then you can use functions directly in setup methods:
https://github.com/EmbeddedRPC/erpc/blob/master/erpc_c/setup/erpc_client_setup.cpp **erpc_client_set_crc** (same number you need set to server)
This number is up to you, but you can let erpcgen generate the number for you.

**Comment by nchokoev** [comment]
But it still calculates the CRC over the whole message in
[https://github.com/EmbeddedRPC/erpc/blob/master/erpc_c/infra/erpc_crc16.cpp](https://github.com/EmbeddedRPC/erpc/blob/master/erpc_c/infra/erpc_crc16.cpp) **computeCRC16(const uint8_t *data, uint32_t lengthInBytes)**

**Comment by Hadatko** [comment]
Yes,
this way server know that message is not corrupted (client crc is sent tos erver, server count its crc and these two crc needs to be same). Default starting value is set at that file to  
Crc16::Crc16(void)
: m_crcStart(**0xEF4A**)
{
}
You can change this as you want, but on both sides. You can use erpcgen to generate this start crc value to be sure that Client IDL and Server IDL is the same ;)

**Comment by nchokoev** [comment]
So, it's not designed to 'bypass' the CRC calculation?
In our case it slows down the transfer of very large binary data frames (100s of MBs), and it's not necessary as we're running it over TCP, which guarantees the data stream integrity.
Would such an option be beneficial?

**Comment by Hadatko** [comment]
Currently everything what is inheriting Framed buffer except RPMSG is doing crc. Currently there is no bypass option.

**Comment by Hadatko** [comment]
As a simple workraund you can copy past crc cpp file and write your own implementation of crc function. It can be empty just returning same value.
