### ISSUE TITLE
"unexpected const" while using erpcgen on example file

### ISSUE THREAD

**Issue by gizmo1904** [EmbeddedRPC/erpc#48]
When I try to use erpcgen on the example IDL file of https://github.com/EmbeddedRPC/erpc/wiki/Getting-Started, this error is thrown: 
`error: file IDL.erpc:10:5: syntax error, unexpected const, expecting '('`

**Comment by gizmo1904** [comment]
Thank you

**Comment by Hadatko** [comment]
Thank you too and sorry for this typo.
