### ISSUE TITLE
unable to call a function(defined in client) from server through function pointer

### ISSUE THREAD

**Issue by jaggi** [EmbeddedRPC/erpc#67]
Hi eRPC team,

firstly ,i tried to call a function(myfun() defined in client,declared in .erpc file) from a server through function call(check line : myfun_resp()  in "test_myfun_server_impl.cpp" file ). Here i am not facing any issues.It is executing that function in the client.  

Next,I am trying to call a function(myfun() defined in client,declared in .erpc file) from a server through function pointer (check line : pcallback(no)  in "test_myfun_server_impl.cpp" file ).But it is not able to execute that function in the client. It doesn't have any compile or run time errors.  

I attached all the files required for you guys to check and help me to solve this issue.

[example.zip](https://github.com/EmbeddedRPC/erpc/files/3475763/example.zip)

**Comment by Hadatko** [comment]
Hi jaggi, i see issues in the code.  In idl you declared 
    callback_t callback; which means that only this function can be passed as pointer to function myFun as parameter.
I think you want to achieve this: replace line 
    myfun_resp(int32 num) -> void with callback_t myfun_resp;
You can remove this line (apt to you. Less generated code): callback_t callback
