### ISSUE TITLE
array of structure is not working in test_arbitrator example

### ISSUE THREAD

**Issue by jaggi** [EmbeddedRPC/erpc#68]
Hi,
I'm passing array of structure from client to server as a parameter of a function and the definition of the same is in  test_arbitrator_server_impl.cpp file. when i compile it gives an error of undefined reference to function.

**Comment by MichalPrincNXP** [comment]
Hi, it is hard to guess, what could be wrong. I do not see any array of structure in test_arbitrator.erpc. Could you provide your modified erpc file and your server implementation?

**Comment by jaggi** [comment]
Hi, 
I got this issue solved. 
Thank you

**Comment by jaggi** [comment]
Hi, 
I got this issue solved. 
Thank you
