### ISSUE TITLE
Outdated version on pypi.org

### ISSUE THREAD

**Issue by ChristianStadelmann** [EmbeddedRPC/erpc#76]
The version on pypi.org is outdated:
* Latest official release: 1.7.2
* Pypi: Version 1.5.0 https://pypi.org/project/erpc/

Is there any reason why pypi doesn't get an updated version?

**Comment by MichalPrincNXP** [comment]
Hi @ChristianStadelmann 
let me check and update ... will let know once the latest version is available.

**Comment by MichalPrincNXP** [comment]
Hi @ChristianStadelmann 
the erpc version on Pypi has been updated to v1.7.2. Could you please try on your side and confirm we could close this issue? Thanks.

**Comment by ChristianStadelmann** [comment]
@MichalPrincNXP : Works fine. Thank you very much!
