### ISSUE TITLE
Static allocated classes

### ISSUE THREAD

**Issue by ablaylock** [EmbeddedRPC/erpc#9]
Why are many of the internal elements of erpc statically allocated with ManuallyConstructed?

I am trying to extract the CRC functionality so that it can be provided to the clients/servers during the erpc_client/server_init() and notice that the MessageBufferFactory, ClientManager, BasicCodeFactory, and Crc16 are all statically allocated and constructed/destroyed with ManuallyConstructed.

If I were to have multiple threads doing RPC to different end points I would think it would be necessary to allow dynamic allocation of these so different threads weren't sharing the resource, especially for something like the CRC.

**Comment by Hadatko** [comment]
Yes that make sense to allow also dynamic allocation. Currently we are focusing on dual-core/processor use cases. That is why we are using static allocated space.
