### ISSUE TITLE
Weak error description when handling error on server side

### ISSUE THREAD

**Issue by Hadatko** [EmbeddedRPC/erpc#97]
```
def handle_invocation(self, methodId, sequence, codec):
        try:
            self._methods[methodId](sequence, codec)
        except KeyError:
            raise RequestError("invalid method ID (%d)" % (methodId))
```

Easy fix is change error message to ("invalid method ID  (%d) or implementation failed"% (methodId))

But this can be confusing for developers (catch theirs errors). I think good option to have could be:
on same place as self._methods is implemented we can have (generated) attribute self._ids = [.....]
This will generate array of ids and we can do this:

```
def handle_invocation(self, methodId, sequence, codec):
     if methodId not in  self._ids:
            raise RequestError("invalid method ID (%d)" % (methodId))        
     self._methods[methodId](sequence, codec)
```

**Comment by MichalPrincNXP** [comment]
@Hadatko , do you plan to create PR?

**Comment by Hadatko** [comment]
I will ;)

**Comment by Hadatko** [comment]
Merged
